language: python

python:
  - 2.6
  - 2.7

env:
  - DJANGO_VERSION=1.4.5

install:
  - pip install django==$DJANGO_VERSION
  - "python setup.py develop"
  - "pip install -r requirements_test.txt --use-mirrors"

script: make test
