language: python

python:
  - 2.6
  - 2.7

env:
  - DJANGO_VERSION=1.3.2
  - DJANGO_VERSION=1.4.1

install:
  - "python setup.py develop"
  - "pip install -r requirements.txt --use-mirrors"

script: make test